### ISSUE TITLE
Is the project abandoned?

### ISSUE THREAD

**Issue by mrkaban** [tkabber/Tkabber-pack#13]
Will there be no more new versions?

Thanks for the program under a free open source license! Added a program to a Russian-language site about free open source software, here is the [link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D0%B8%D0%BD%D1%82%D0%B5%D1%80%D0%BD%D0%B5%D1%82/%D0%BE%D0%B1%D1%89%D0%B5%D0%BD%D0%B8%D0%B5/tkabber-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82-%D0%BC%D0%B3%D0%BD%D0%BE%D0%B2%D0%B5%D0%BD%D0%BD%D0%BE%D0%B3%D0%BE-%D0%BE%D0%B1%D0%BC%D0%B5%D0%BD%D0%B0-%D1%81%D0%BE%D0%BE%D0%B1%D1%89%D0%B5%D0%BD%D0%B8%D1%8F%D0%BC%D0%B8.html).

Please do not abandon the project! This is a very interesting program!

Will stable versions be published here?

**Comment by vitalyster** [comment]
You miss the main point of open source software - you always can get the source and continue development, so it can not be "abandoned"
