### ISSUE TITLE
Publication of all Tkabber repositories here

### ISSUE THREAD

**Issue by Neustradamus** [tkabber/Tkabber-pack#14]
@Totktonada: Can you publish all Tkabber repositories in this organization?

All people are in the organization?
@alexeyshch (Alexey Shchepin), @sgolovan (Sergei Golovan), @kostix (Konstantin Khomoutov), @badlop

Repositories:
- https://chiselapp.com/user/sgolovan/repository/tclxmpp
- https://chiselapp.com/user/sgolovan/repository/tkabber
- https://chiselapp.com/user/sgolovan/repository/tkabber-plugins
- https://chiselapp.com/user/sgolovan/repository/tkabber-contrib

Thanks in advance.

**Comment by vitalyster** [comment]
chiselapp hosting with Fossil support was chosen for Tkabber development explicitly.

**Comment by Neustradamus** [comment]
@vitalyster: Hard to talk with you, do you received my private messages?

Originally, these questions were not for you.

But it is possible to add me in this organization?
I will manage directly this organization, thanks in advance.

**Comment by Totktonada** [comment]
Vitaly is the person who creates this GitHub organization (primarily to develop the Windows packaging tool).

Sure, tkabber itself is developed on the chiselapp and that's decision of Sergey — he is the main developer today.

I don't mind mirroring, but there are no much sense in synching the repositories once. If we'll do, we should setup continuous mirroring. And it'll be read only mirrors, so all 'social coding' GitHub features will not be in use.

Anyway, I want to know the purpose. How you intend to use those mirrors?
